import mongoose from "mongoose";

const vendorSchema = new mongoose.Schema({
  // Unique vendor identifier (UUID generated by system)
  vendorId: {
    type: String,
    required: true,
    unique: true,
  },

  // Short ID embedded inside QR code
  qrId: {
    type: String,
    required: true,
    unique: true,
  },

  // Basic vendor information
  firstName: {
    type: String,
    required: true,
  },

  lastName: {
    type: String,
    required: true,
  },

  shopName: {
    type: String,
    required: true,
  },

  // Login credentials
  email: {
    type: String,
    required: true,
    unique: true,
  },

  passwordHash: {
    type: String,
    required: true,
  },

  // Account status
  status: {
    type: String,
    enum: ["active", "blocked"],
    default: "active",
    index: true,
  },

  // QR code image URL (generated later)
  qrCodeUrl: {
    type: String,
  },

  // UI preferences
  preferences: {
    viewMode: {
      type: String,
      enum: ["grid", "list"],
      default: "grid",
    },
    sidebarWidth: {
      type: Number,
      default: 240,
    },
  },

  // Metadata
  createdAt: {
    type: Date,
    default: Date.now,
  },

  isActive: {
    type: Boolean,
    default: true,
  },

  tokenInvalidBefore: {
  type: Date,
  default: null,
},

});

export default mongoose.model("Vendor", vendorSchema);
